
# Cache definition for the cargo package cache.
# Pull only by default - the fetch-deps job will update the cache for each build.
.pkg_cache: &pkg_cache
  key: "pkgcache-$CI_COMMIT_REF_SLUG"
  paths:
    - .cargo/
  policy: pull

.on_default_branch:
  - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.on_tags:
  - if: '$CI_COMMIT_TAG'

.allow_manual_run:
  - when: manual
    allow_failure: true

.on_ready_mrs:
  - if: '$CI_MERGE_REQUEST_TITLE =~ /^WIP:.*/'
    when: never
  - if: '$CI_MERGE_REQUEST_TITLE =~ /^Draft:.*/'
    when: never
  - if: '$CI_MERGE_REQUEST_ID'