stages:
  - build
  - test
  - docs
  - binary
  - imagebuilder

image: rust:latest

cache:
  paths:
    - .cargo/

before_script:
  - apt-get update && apt-get install -y libavahi-compat-libdnssd-dev cmake clang
  - export CARGO_HOME=${CI_PROJECT_DIR}/.cargo
  - wget -o /dev/null https://github.com/mozilla/sccache/releases/download/0.2.13/sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
  - tar -xzf sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
  - export RUSTC_WRAPPER=${CI_PROJECT_DIR}/sccache-0.2.13-x86_64-unknown-linux-musl/sccache
  - export SCCACHE_DIR=${CI_PROJECT_DIR}/.cargo/sccache
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/namib_shared.git --branch ${CI_COMMIT_BRANCH} ../namib_shared || git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/namib_shared.git ../namib_shared
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/rust-async-dnssd.git ../rust-async-dnssd
  - git clone --recurse-submodules https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/libuci-sys.git ../libuci-sys
  - rustc --version
  - cargo --version

default:
  tags:
    - linux
    - docker

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo test

warnings:
  stage: test
  script:
    - rustup toolchain install nightly --component clippy --no-self-update
    - cargo +nightly clippy -- -D warnings
  allow_failure: true

formatting:
  stage: test
  script:
    - rustup toolchain install nightly --component rustfmt --no-self-update
    - cargo +nightly fmt -- --check

docs:
  stage: docs
  except:
    - master
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc
    expire_in: 7 days

pages:
  stage: docs
  only:
    - master
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=namib_enforcer/index.html">' > public/index.html
  artifacts:
    paths:
      - public
    expire_in: 7 days

binary:
  stage: binary
  only:
    - master
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/namib_enforcer
      - target/release/namib_dnsmasq_hook
    expire_in: 7 days

openwrt_package_x86_64:
  extends: .openwrt_package_base
  image: openwrtorg/sdk:x86_64-19.07.4
  variables:
    RUST_TRIPLE: x86_64-unknown-linux-musl

openwrt_package_bcm2708: # raspberry v1
  extends: .openwrt_package_base
  image: openwrtorg/sdk:brcm2708-bcm2708-19.07.4
  variables:
    RUST_TRIPLE: arm-unknown-linux-musleabihf

openwrt_package_bcm2710: # raspberry v3
  extends: .openwrt_package_base
  image: openwrtorg/sdk:brcm2708-bcm2710-19.07.4
  variables:
    RUST_TRIPLE: aarch64-unknown-linux-musl

openwrt_package_bcm2710_snapshot: # raspberry v3
  extends: .openwrt_package_base
  image: openwrtorg/sdk:bcm27xx-bcm2710-snapshot
  variables:
    RUST_TRIPLE: aarch64-unknown-linux-musl

.openwrt_package_base:
  stage: binary
  dependencies: [ ]
  cache: { }
  only:
    - master
  before_script: [ ]
  script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal -t $RUST_TRIPLE
    - source $HOME/.cargo/env
    - sudo apt-get update && sudo apt-get install -y clang libc6-dev-i386 --no-install-recommends # build dependency for bindgen
    - cd /home/build/openwrt
    - ./scripts/feeds update base packages
    - ./scripts/feeds install libavahi-compat-libdnssd libuci openssl
    - cd /home/build/openwrt
    - mv ${CI_PROJECT_DIR}/openwrt/config.diff .config
    - mv ${CI_PROJECT_DIR}/openwrt ./package/namib
    - mkdir package/namib/src
    - cd package/namib/src
    - cp -r ${CI_PROJECT_DIR} namib_enforcer
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/namib_shared.git --branch ${CI_COMMIT_BRANCH} || git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/namib_shared.git
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/rust-async-dnssd.git
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/libuci-sys.git
    - cd namib_shared/certs
    - ./gen_ca.sh
    - ./gen_client_cert.sh
    - cd /home/build/openwrt
    - make defconfig
    - make package/namib/compile -j8
  after_script:
    - mkdir ${CI_PROJECT_DIR}/output
    - cp -r /home/build/openwrt/logs/package/namib ${CI_PROJECT_DIR}/output/logs || true
    - cp -r /home/build/openwrt/bin/packages/*/base/namib_0.1.0-*.ipk /home/build/openwrt/package/namib/src/namib_shared/certs ${CI_PROJECT_DIR}/output || true
  artifacts:
    paths:
      - output
    when: always

imagebuilder:
  stage: imagebuilder
  trigger:
    include:
      - project: namib/mud-controller-enforcer/controller-enforcer-metaproject
        ref: master
        file: .gitlab-ci.imagebuilder.yml
    strategy: depend