include:
  - local: namib_controller/.gitlab-ci.yml
  - local: namib_enforcer/.gitlab-ci.yml
  - local: namib_shared/.gitlab-ci.yml

stages:
  - build
  - test
  - binary
  - imagebuilder
  - docs
  - release
  - gh-release
  - docker

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

image: gitlab.informatik.uni-bremen.de:5005/namib-master/ci-docker-images/controller:generic

cache:
  paths:
    - .cargo/

default:
  tags:
    - linux
    - docker
  retry: 2

variables:
  KUBERNETES_CPU_REQUEST: 3
  KUBERNETES_CPU_LIMIT: 5
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 4Gi
  KUBERNETES_SERVICE_CPU_REQUEST: 200m
  KUBERNETES_SERVICE_CPU_LIMIT: 400m
  KUBERNETES_SERVICE_MEMORY_REQUEST: 512Mi
  KUBERNETES_SERVICE_MEMORY_LIMIT: 1Gi
  FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY: "false"
