stages:
  - build
  - test
  - docs

image: rustlang/rust:nightly-slim

cache:
  paths:
    - .cargo/

before_script:
  - apt-get update && apt-get install -y wget git openssl libavahi-compat-libdnssd-dev
  - export CARGO_HOME=${CI_PROJECT_DIR}/.cargo
  - wget -o /dev/null https://github.com/mozilla/sccache/releases/download/0.2.13/sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
  - tar -xzf sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
  - export RUSTC_WRAPPER=${CI_PROJECT_DIR}/sccache-0.2.13-x86_64-unknown-linux-musl/sccache
  - export SCCACHE_DIR=${CI_PROJECT_DIR}/.cargo/sccache
  - git clone https://gitlab-ci-token:${namib_shared_access_token}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/namib_shared.git ../namib_shared
  - git clone https://gitlab-ci-token:${namib_async_dnssd_access_token}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/rust-async-dnssd.git ../rust-async-dnssd
  - rustc --version
  - cargo --version

default:
  tags:
    - linux
    - docker

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo test

warnings:
  stage: test
  script:
    - cargo clippy -- -D warnings
  allow_failure: true

formatting:
  stage: test
  script:
    - cargo fmt -- --check

docs:
  stage: docs
  except:
    - master
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc
    expire_in: 7 days

pages:
  stage: docs
  only:
    - master
  script:
    - cargo doc --no-deps
    - mv target/doc ../public
    - echo '<meta http-equiv="refresh" content="0; url=namib_mud_controller/index.html">' > ../public/index.html
  artifacts:
    paths:
      - public
    expire_in: 7 days