stages:
  - build
  - test
  - docs
  - docker

image: rust:latest

cache:
  paths:
    - .cargo/

before_script:
  - git config --global credential.helper store
  - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de" > ~/.git-credentials
  - apt-get update && apt-get install -y libavahi-compat-libdnssd-dev
  - export CARGO_HOME=${CI_PROJECT_DIR}/.cargo
  - wget -o /dev/null https://github.com/mozilla/sccache/releases/download/0.2.13/sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
  - tar -xzf sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
  - export RUSTC_WRAPPER=${CI_PROJECT_DIR}/sccache-0.2.13-x86_64-unknown-linux-musl/sccache
  - export SCCACHE_DIR=${CI_PROJECT_DIR}/.cargo/sccache
  - rustup toolchain install nightly --component rustfmt,clippy --no-self-update
  - rustup default nightly
  - rustc --version
  - cargo --version

default:
  tags:
    - linux
    - docker

build:
  stage: build
  script:
    - cargo build

build-release:
  stage: build
  #only:
  #  - master
  script:
    - cargo build --release
    - cargo install --root ./install --path .
    - pushd ../namib_shared/certs/
    - ./gen_ca.sh
    - ./gen_server_cert.sh
    - popd
    - mkdir -p ./namib_shared/certs
    - cp ../namib_shared/certs/ca.pem ./namib_shared/certs/
  artifacts:
    paths:
      - install/bin
      - certs
      - Dockerfile
      - namib_shared

test:
  stage: test
  script:
    - cargo test

warnings:
  stage: test
  script:
    - cargo +nightly clippy -- -D warnings
  allow_failure: true

formatting:
  stage: test
  script:
    - cargo +nightly fmt -- --check

docs:
  stage: docs
  except:
    - master
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc
    expire_in: 7 days

pages:
  stage: docs
  only:
    - master
  script:
    - cargo doc --no-deps
    - mv target/doc ../public
    - echo '<meta http-equiv="refresh" content="0; url=namib_mud_controller/index.html">' > ../public/index.html
  artifacts:
    paths:
      - public
    expire_in: 7 days

create-docker:
  stage: docker
  before_script:
    - echo "Global before_script disabled"
  dependencies:
    - build-release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - ls -lashR
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $CI_REGISTRY_IMAGE:latest
  #only:
  #  - master
