image: 'rust:latest'

stages:
  - build
  - docs

build:
  stage: build
  tags:
    - linux
    - docker
  script:
    - rustc --version
    - cargo --version
    - cargo build

docs:
  stage: docs
  tags:
    - linux
    - docker
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0;">' > public/index.html
    - ls public
  only:
    - master
