stages:
  - build
  - test
  - docs

image: rustlang/rust:nightly

cache:
  paths:
    - .cargo/

before_script:
  - apt-get update && apt-get install -y libavahi-compat-libdnssd-dev cmake clang
  - export CARGO_HOME=${CI_PROJECT_DIR}/.cargo
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/namib_shared.git --branch ${CI_COMMIT_BRANCH} ${CI_BUILDS_DIR}/namib_shared || git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/namib_shared.git ${CI_BUILDS_DIR}/namib_shared
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/rust-async-dnssd.git ${CI_BUILDS_DIR}/rust-async-dnssd
  - git clone --recurse-submodules https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/libuci-sys.git ${CI_BUILDS_DIR}/libuci-sys
  - rustc --version
  - cargo --version

default:
  tags:
    - linux
    - docker

build:
  stage: build
  script:
    - cargo build
  artifacts:
    paths:
      - target
    expire_in: 7 days

test:
  stage: test
  script:
    - cargo test

test_warnings:
  stage: test
  script:
    - cargo clippy -- -D warnings

docs:
  stage: docs
  except:
    - master
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc
    expire_in: 7 days

pages:
  stage: docs
  only:
    - master
  script:
    - cargo doc --no-deps
    - mv target/doc ../public
    - echo '<meta http-equiv="refresh" content="0; url=namib_enforcer/index.html">' > ../public/index.html
  artifacts:
    paths:
      - public
    expire_in: 7 days

