stages:
  - build
  - test
  - docs

image: rustlang/rust:nightly

cache:
  paths:
    - .cargo/

before_script:
  - apt-get update && apt-get install -y libavahi-compat-libdnssd-dev cmake clang
  - export CARGO_HOME=${CI_PROJECT_DIR}/.cargo
  - mkdir namib_enforcer
  - shopt -s extglob
  - mv !(namib_enforcer) namib_enforcer
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/namib_shared.git --branch ${CI_COMMIT_BRANCH} || git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/namib_shared.git
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/rust-async-dnssd.git
  - git clone --recurse-submodules https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/libuci-sys.git
  - cd namib_enforcer
  - rustc --version
  - cargo --version

default:
  tags:
    - linux
    - docker

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo test

pages:
  stage: docs
  script:
    - cargo doc --no-deps
    - mv target/doc ../public
    - echo '<meta http-equiv="refresh" content="0; url=namib_enforcer/index.html">' > ../public/index.html
  artifacts:
    paths:
      - public
    expire_in: 7 days
