stages:
  - build
  - test
  - docs

image: rustlang/rust:nightly

cache:
  paths:
    - .cargo/

before_script:
  - apt-get update && apt-get install -y libavahi-compat-libdnssd-dev
  - export CARGO_HOME=${CI_PROJECT_DIR}/.cargo
  - mkdir namib_mud_controller
  - shopt -s extglob
  - mv !(namib_mud_controller) namib_mud_controller
  - git clone https://gitlab-ci-token:${namib_shared_access_token}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/namib_shared.git
  - git clone https://gitlab-ci-token:${namib_async_dnssd_access_token}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/rust-async-dnssd.git
  - cd namib_mud_controller
  - rustc --version
  - cargo --version

default:
  tags:
    - linux
    - docker

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo test

pages:
  stage: docs
  script:
    - cargo doc --no-deps
    - mv target/doc ../public
    - echo '<meta http-equiv="refresh" content="0; url=namib_mud_controller/index.html">' > ../public/index.html
  artifacts:
    paths:
      - public
    expire_in: 7 days