include:
  - local: namib_controller/.gitlab-ci.yml
  - local: namib_enforcer/.gitlab-ci.yml
  - local: namib_shared/.gitlab-ci.yml
  - local: .common.yml

stages:
  - prepare
  - build
  - test
  - package
  - docs
  - release

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

image: gitlab.informatik.uni-bremen.de:5005/namib-master/ci-docker-images/controller:generic

default:
  tags:
    - linux
    - docker
    - kubernetes
  # retry: 2

fetch-deps:
  stage: prepare
  cache:
    - key: !reference [.pkg_cache, key]
      paths: !reference [.pkg_cache, paths]
      policy: pull-push
  script:
    - cargo fetch --locked


variables:
  KUBERNETES_CPU_REQUEST: 4
  CARGO_BUILD_JOBS: 4
#  KUBERNETES_CPU_LIMIT: 5
  KUBERNETES_MEMORY_REQUEST: 4Gi
  KUBERNETES_MEMORY_LIMIT: 4Gi
#  KUBERNETES_SERVICE_CPU_REQUEST: 400m
#  KUBERNETES_SERVICE_CPU_LIMIT: 400m
#  KUBERNETES_SERVICE_MEMORY_REQUEST: 1Gi
#  KUBERNETES_SERVICE_MEMORY_LIMIT: 1Gi
#  FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY: "false"
#  FALLBACK_CACHE_KEY: "main"
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
  FF_USE_FASTZIP: "true"
  CACHE_COMPRESSION_LEVEL: fast
  TRANSFER_METER_FREQUENCY: 5s
