image: 'rust:latest'

stages:
  - build
  - docs

build:
  stage: build
  tags:
    - linux
    - docker
  script:
    - rustc --version
    - cargo --version
    - cargo build

warnings:
  stage: test
  script:
    - cargo clippy -- -D warnings
  allow_failure: true

docs:
  stage: docs
  except:
    - master
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc
    expire_in: 7 days

pages:
  stage: docs
  only:
    - master
  script:
    - cargo doc --no-deps
    - mv target/doc ../public
    - echo '<meta http-equiv="refresh" content="0; url=namib_shared/index.html">' > ../public/index.html
  artifacts:
    paths:
      - public
    expire_in: 7 days