stages:
  - build
  - test
  - docs

default:
  image: rustlang/rust:nightly-slim
  cache:
    paths:
      - .cargo/
  before_script:
    - export CARGO_HOME=${CI_PROJECT_DIR}/cargo
    - mkdir namib_enforcer
    - shopt -s extglob
    - mv !(namib_enforcer) namib_enforcer
    - git clone https://gitlab-ci-token:${namib_shared_access_token}@gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/namib_shared.git
    - cd namib_enforcer
    - rustc --version
    - cargo --version
  tags:
    - linux
    - docker

build:
  stage: build
  artifacts:
    paths:
      - target
  script:
    - cargo build

test:
  stage: test
  dependencies:
    - build
  script:
    - cargo test

docs:
  stage: docs
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0;">' > public/index.html
    - ls public
  only:
    - master
