[package]
name = "namib_mud_controller"
version = "0.0.1"
authors = ["Jeffrey Munstermann <jemu@uni-bremen.de>", "Benjamin Ludewig <ludewigb@uni-bremen.de>", "Hugo Hakim Damer <hdamer@uni-bremen.de>", "Florian Bonetti <flobon@uni-bremen.de>", "Michael Bach <bachm@uni-bremen.de>"]
edition = "2018"

[features]
default = ["sqlite"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]

[dependencies]
funty = "=1.1.0" # Temporary fix for building bitvec (https://github.com/bitvecto-rs/bitvec/issues/105#issuecomment-778570981)
actix-web = "3.3"
actix-rt = "1.1"
actix-files = "0.5"
actix-cors = "0.5.4"
actix-ratelimit = { version = "0.3.1", default-features = false, features = ["memory"] }
sqlx = { version = "0.4", features = ["runtime-actix-rustls", "chrono"] }
namib_shared = { tag = "0.3.1", git = "https://gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/namib_shared.git" }
log = "0.4"
env_logger = "0.8"
tokio = { version = "1", features = ["full"] }
async-dnssd = { tag = "0.5.0-rc.3", git = "https://gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/rust-async-dnssd.git" }
futures = "0.3"
rustls = "0.19"
tokio-rustls = "0.22"
tokio-util = "0.6"
tokio-serde = "0.8"
tarpc = { version = "0.24", features = ["full"] }
pin-project = "1.0"
rand = "0.8"
rust-argon2 = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
dotenv = "0.15"
jsonwebtoken = "7.2"
chrono = { version = "0.4", features = ["serde"] }
validator = { version = "0.12", features = ["derive"] }
snafu = { version = "0.6", default-features = false, features = ["std", "backtraces", "futures"] }
isahc = "1.0"
paperclip = { version = "0.5", features = ["actix", "chrono"] }
glob = "0.3"
const_format = "0.2"
strum = { version = "0.20", features = ["derive"] }
strum_macros = { version = "0.20" }
sha-1 = "0.9"
base64 = "0.13"
regex = "1"
lazy_static = "1"
clokwerk = "0.3.4"
url = "2"
tokio-compat-02 = "0.2"
neo4jthings-api = { path = "neo4jthings-api" }