[package]
name = "namib_shared"
version = "0.2.1"
authors = ["Jeffrey Munstermann <jemu@uni-bremen.de>", "Benjamin Ludewig <ludewigb@uni-bremen.de>", "Hugo Hakim Damer <hdamer@uni-bremen.de>", "Florian Bonetti <flobon@uni-bremen.de>", "Michael Bach <bachm@uni-bremen.de>"]
edition = "2018"

[dependencies]
snafu = "0.6"
tokio-serde = { version = "0.8", features = ["bincode"] }
tarpc = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }
macaddr = { version = "1.0.1", features = ["serde_std"] }
schemars = { version = "0.8", features = ["chrono"] }
hex = "0.4"
