include:
  - local: /.common.yml

.shd:job_base:
  rules:
    - !reference [.on_tags]
    - !reference [.on_default_branch]
    - &on_enforcer_change changes: ["namib_shared/**/*"]
    - !reference [.allow_manual_run]
  cache:
    - !reference [.pkg_cache]
    - &shared_cache
      key: "shared-native-$CI_COMMIT_REF_SLUG"
      paths:
        - target/*/deps/
        - target/*/incremental/
        - target/*/build/
      policy: pull

  before_script:
    - rustc --version
    - cargo --version

shd:build:
  extends: .shd:job_base
  stage: build
  cache:
    - !reference [.pkg_cache]
    - <<: *shared_cache
      policy: pull-push
  script:
    - cargo build -p namib_shared

shd:test:
  extends: .shd:job_base
  stage: test
  needs:
    - job: shd:build
      artifacts: false
  script:
    - cargo test -p namib_shared -- -Z unstable-options --format json --report-time | tee results.json
    - cat results.json | cargo2junit > target/shared-test-results.xml
  artifacts:
    reports:
      junit: target/shared-test-results.xml
  allow_failure: true

shd:coverage:
  extends: .shd:job_base
  stage: test
  rules:
    - !reference [.on_tags]
    - !reference [.on_default_branch]
    - !reference [.on_ready_mrs]
    - !reference [.allow_manual_run]
  needs:
    - job: shd:build
      artifacts: false
  script:
    - cargo tarpaulin -p namib_shared --out Xml
    - mv cobertura.xml target/shared-coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/shared-coverage.xml
  allow_failure: true

shd:warnings:
  extends: .shd:job_base
  stage: test
  needs:
    - job: shd:build
      artifacts: false
  script:
    - cargo clippy -p namib_shared -- -D warnings
  after_script:
    - cargo clippy -p namib_shared --message-format=json | gitlab-clippy > target/shared-code-quality.json
  artifacts:
    reports:
      codequality: target/shared-code-quality.json
  allow_failure: true

shd:formatting:
  extends: .shd:job_base
  stage: test
  needs:
    - job: shd:build
      artifacts: false
  script:
    - cargo fmt -p namib_shared -- --check