include:
  - local: /.common.yml

.shd:job_base:
  rules:
    - changes: ["namib_shared/**/*"]
  cache:
    - !reference [.pkg_cache]
    - &shared_cache
      key: "shared-native-$CI_COMMIT_REF_SLUG"
      paths:
        - target/*/deps/
        - target/*/incremental/
        - target/*/build/
      policy: pull

  before_script:
    - rustc --version
    - cargo --version

shd:build:
  extends: .shd:job_base
  stage: build
  cache:
    - !reference [.pkg_cache]
    - <<: *shared_cache
      policy: pull-push
  script:
    - cargo build -p namib_shared

shd:test:
  extends: .shd:job_base
  stage: test
  needs:
    - shd:build
  script:
    - cargo test -p namib_shared
  allow_failure: true

shd:warnings:
  extends: .shd:job_base
  stage: test
  needs:
    - shd:build
  script:
    - cargo clippy -p namib_shared -- -D warnings
  allow_failure: true

shd:formatting:
  extends: .shd:job_base
  stage: test
  needs:
    - shd:build
  script:
    - cargo fmt -p namib_shared -- --check