include:
  - local: ////.common.yml

enf:openwrt-package_x86_64_21.02:
  extends: .enf:openwrt_package_base
  image: gitlab.informatik.uni-bremen.de:5005/namib-master/ci-docker-images/controller/openwrt_sdk:21.02.3-x86_64
  variables:
    RUST_TRIPLE: x86_64-unknown-linux-musl
    CI_OPENWRT_RELEASE: "21.02"

enf:openwrt-package_bcm2708_21.02: # raspberry v1
  extends: .enf:openwrt_package_base
  image: gitlab.informatik.uni-bremen.de:5005/namib-master/ci-docker-images/controller/openwrt_sdk:21.02.3-bcm27xx-bcm2708
  variables:
    RUST_TRIPLE: arm-unknown-linux-musleabihf
    CI_OPENWRT_RELEASE: "21.02"

enf:openwrt-package_bcm2710_21.02: # raspberry v3
  extends: .enf:openwrt_package_base
  image: gitlab.informatik.uni-bremen.de:5005/namib-master/ci-docker-images/controller/openwrt_sdk:21.02.3-bcm27xx-bcm2710
  variables:
    RUST_TRIPLE: aarch64-unknown-linux-musl
    CI_OPENWRT_RELEASE: "21.02"

enf:openwrt-package_bcm2711_21.02: # raspberry v4
  extends: .enf:openwrt_package_base
  image: gitlab.informatik.uni-bremen.de:5005/namib-master/ci-docker-images/controller/openwrt_sdk:21.02.3-bcm27xx-bcm2711
  variables:
    RUST_TRIPLE: aarch64-unknown-linux-musl
    CI_OPENWRT_RELEASE: "21.02"

enf:openwrt-package_x86_64_22.03:
  extends: .enf:openwrt_package_base
  image: gitlab.informatik.uni-bremen.de:5005/namib-master/ci-docker-images/controller/openwrt_sdk:22.03-SNAPSHOT-x86_64
  variables:
    RUST_TRIPLE: x86_64-unknown-linux-musl
    CI_OPENWRT_RELEASE: "22.03"

enf:openwrt-package_bcm2708_22.03: # raspberry v1
  extends: .enf:openwrt_package_base
  image: gitlab.informatik.uni-bremen.de:5005/namib-master/ci-docker-images/controller/openwrt_sdk:22.03-SNAPSHOT-bcm27xx-bcm2708
  variables:
    RUST_TRIPLE: arm-unknown-linux-musleabihf
    CI_OPENWRT_RELEASE: "22.03"

enf:openwrt-package_bcm2710_22.03: # raspberry v3
  extends: .enf:openwrt_package_base
  image: gitlab.informatik.uni-bremen.de:5005/namib-master/ci-docker-images/controller/openwrt_sdk:22.03-SNAPSHOT-bcm27xx-bcm2710
  variables:
    RUST_TRIPLE: aarch64-unknown-linux-musl
    CI_OPENWRT_RELEASE: "22.03"

enf:openwrt-package_bcm2711_22.03: # raspberry v4
  extends: .enf:openwrt_package_base
  image: gitlab.informatik.uni-bremen.de:5005/namib-master/ci-docker-images/controller/openwrt_sdk:22.03-SNAPSHOT-bcm27xx-bcm2711
  variables:
    RUST_TRIPLE: aarch64-unknown-linux-musl
    CI_OPENWRT_RELEASE: "22.03"

.enf:openwrt_package_base:
  stage: package
  needs: []
  rules:
    - !reference [.on_tags]
    - !reference [.on_default_branch]
    - !reference [.allow_manual_run]
  before_script:
    # setup https credentials
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de" > ~/.git-credentials
    # decrypt ca secret
    - gpg --import $GPG_PRIVATE_KEY
    - git secret reveal
    - cd certs
    - ./gen_client_cert.sh namib-ca
  script:
    - cd /home/build/openwrt
    - ./scripts/feeds update base packages
    - ./scripts/feeds install libavahi-compat-libdnssd libuci openssl nftables dnsmasq-full libnetfilter-log
    - mv "${CI_PROJECT_DIR}/namib_enforcer/openwrt/package/config.diff" .config
    - mv "${CI_PROJECT_DIR}/namib_enforcer/openwrt/package/dnsmasq_patches_${CI_OPENWRT_RELEASE}/"* package/feeds/base/dnsmasq/patches/
    - mv "${CI_PROJECT_DIR}/namib_enforcer/openwrt/package" ./package/namib
    - ln -s "${CI_PROJECT_DIR}" package/namib/src
    - mkdir output
    - make defconfig
    - make package/namib/compile -j8 | tee output/namib_compile.txt
    - make package/feeds/base/dnsmasq/compile -j8 | tee output/dnsmasq_compile.txt
  after_script:
    - mkdir ${CI_PROJECT_DIR}/output
    - cp -r /home/build/openwrt/logs/package/namib ${CI_PROJECT_DIR}/output/logs || true
    - cp -r /home/build/openwrt/bin/packages/*/base/namib_0.1.0-*.ipk ${CI_PROJECT_DIR}/output || true
    - cp -r /home/build/openwrt/bin/packages/*/base/dnsmasq-full_*.ipk ${CI_PROJECT_DIR}/output || true
  artifacts:
    when: always
    paths:
      - output

    when: always
