/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Acl {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub _type: String,
    #[serde(rename = "acl_dns")]
    pub acl_dns: String,
    #[serde(rename = "port")]
    pub port: Vec<i32>,
    #[serde(rename = "direction_initiated")]
    pub direction_initiated: String,
    #[serde(rename = "forwarding")]
    pub forwarding: String,
    #[serde(rename = "timestamp")]
    pub timestamp: Option<String>,
}

impl Acl {
    pub fn new(name: String, _type: String, acl_dns: String, port: Vec<i32>, direction_initiated: String, forwarding: String, timestamp: Option<String>) -> Acl {
        Acl {
            name,
            _type,
            acl_dns,
            port,
            direction_initiated,
            forwarding,
            timestamp,
        }
    }
}


