/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mud {
    #[serde(rename = "mud_version")]
    pub mud_version: i32,
    #[serde(rename = "mud_url")]
    pub mud_url: String,
    #[serde(rename = "mud_signature")]
    pub mud_signature: String,
    #[serde(rename = "cache_validity")]
    pub cache_validity: i32,
    #[serde(rename = "systeminfo")]
    pub systeminfo: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "firmware_rev")]
    pub firmware_rev: String,
    #[serde(rename = "software_rev")]
    pub software_rev: String,
    #[serde(rename = "documentation")]
    pub documentation: String,
}

impl Mud {
    pub fn new(mud_version: i32, mud_url: String, mud_signature: String, cache_validity: i32, systeminfo: String, name: String, firmware_rev: String, software_rev: String, documentation: String) -> Mud {
        Mud {
            mud_version,
            mud_url,
            mud_signature,
            cache_validity,
            systeminfo,
            name,
            firmware_rev,
            software_rev,
            documentation,
        }
    }
}


