version: "3"

services:
  namib_mud_controller:
    image: gitlab.informatik.uni-bremen.de:5005/namib/mud-controller-enforcer/namib_mud_controller:latest
    volumes:
      - ./acme:/namib/acme
    ports:
      - 8000:8000
      - 8734:8734
    networks:
      - lan

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: namib
      POSTGRES_PASSWORD: namib
    ports:
      - 5432:5432
    networks:
      - lan

  namib_enforcer:
    image: gitlab.informatik.uni-bremen.de:5005/namib/mud-controller-enforcer/namib_enforcer
    tty: true
    cap_add:
      - NET_ADMIN
    ports:
      - 5480:80
    networks:
      lan:
      wan:
        priority: 100

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/test
    networks:
      - lan

  neo4things:
    image: gitlab.informatik.uni-bremen.de:5005/namib/gruppe-1-legacy-nodes/neo4things:master
    entrypoint:
      - sh
      - -c
      - >
        python manage.py install_labels;
        python manage.py migrate;
        echo "from django.contrib.auth import get_user_model; get_user_model().objects.create_superuser('admin', 'admin@namib.me', 'namib')" | python manage.py shell;
        exec /app/neogit/docker-entrypoint.sh
    ports:
      - 7000:8000
    environment:
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: test
      NEO4J_HOST: neo4j
      NEO4J_PORT: 7687
      NEO4J_BOLT_URL: bolt://neo4j:test@neo4j:7687
      SECRET_KEY: asecret
    networks:
      - lan

networks:
  wan:
  lan: