image: rust:1.52

cache:
  paths:
    - .cargo/

variables:
  KUBERNETES_CPU_REQUEST: 3
  KUBERNETES_CPU_LIMIT: 5
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 4Gi
  KUBERNETES_SERVICE_CPU_REQUEST: 200m
  KUBERNETES_SERVICE_CPU_LIMIT: 400m
  KUBERNETES_SERVICE_MEMORY_REQUEST: 512Mi
  KUBERNETES_SERVICE_MEMORY_LIMIT: 1Gi
  FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY: "false"

before_script:
  - apt-get update && apt-get install -y libavahi-compat-libdnssd-dev
  - git config --global credential.helper store
  - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de" > ~/.git-credentials
  - export CARGO_HOME=${CI_PROJECT_DIR}/.cargo
  - rustc --version
  - cargo --version
  - cargo install sqlx-cli
  - export PATH=$PATH:$CARGO_HOME/bin
  - ./scripts/recreate_db.sh

default:
  tags:
    - linux
    - docker
  retry: 2

build:
  extends: .namib_controller_base
  stage: build
  script:
    - cargo build

test:
  extends: .namib_controller_base
  stage: test
  script:
    - cargo test

test-postgres:
  extends: .namib_controller_base
  stage: test
  services:
    - postgres
  variables:
    MIGRATION_DIRECTORY: migrations/postgres
    POSTGRES_USER: namib
    POSTGRES_PASSWORD: namib
    DATABASE_URL: postgres://namib:namib@postgres/namib_mud_controller
  script:
    - cargo test --no-default-features --features postgres

warnings:
  extends: .namib_controller_base
  stage: test
  script:
    - rustup toolchain install nightly --component clippy --no-self-update
    - cargo +nightly clippy -- -D warnings
  retry: 0
  allow_failure: true

formatting:
  extends: .namib_controller_base
  stage: test
  script:
    - rustup toolchain install nightly --component rustfmt --no-self-update
    - cargo +nightly fmt -- --check

.test_stage:
  - test
  - test-postgres
  - formatting

docs:
  extends: .namib_controller_base
  stage: docs
  needs:
    - build
  except:
    - master
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc
    expire_in: 7 days

pages:
  extends: .namib_controller_base
  stage: docs
  needs: !reference [.test_stage]
  only:
    refs:
      - main
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=namib_mud_controller/index.html">' > public/index.html
  artifacts:
    paths:
      - public
    expire_in: 7 days

build-release:
  extends: .build-release-base
  variables:
    FEATURES: ""

build-release-postgres:
  extends: .build-release-base
  services:
    - postgres
  variables:
    FEATURES: "--no-default-features --features postgres"
    MIGRATION_DIRECTORY: migrations/postgres
    POSTGRES_USER: namib
    POSTGRES_PASSWORD: namib
    DATABASE_URL: postgres://namib:namib@postgres/namib_mud_controller

.build-release-base:
  extends: .namib_controller_base
  stage: release
  needs: []
  only:
    refs:
      - main
  cache:
    key: "build-release"
  script:
    - cargo install --root ./install --path . $FEATURES
    # download namib frontend
    - ./scripts/download_namib_frontend.sh
    # decrypt ca secret
    - apt-get install git-secret -y
    - gpg --import $GPG_PRIVATE_KEY
    - cd ..
    - git init && git remote add origin https://gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/controller-enforcer-metaproject.git
    - git fetch origin && git checkout origin/master -f
    - git secret reveal
    - cd certs
    - ./gen_server_cert.sh namib-ca
  artifacts:
    paths:
      - install/bin
      - certs
      - static
      - db.sqlite

.build-release-debian:
  extends: .namib_controller_base
  stage: release
  needs: []
  only:
    refs:
      - main
      - tags
  services:
    - postgres
  cache:
    key: "build-release"
  variables:
    MIGRATION_DIRECTORY: migrations/postgres
    POSTGRES_USER: namib
    POSTGRES_PASSWORD: namib
    DATABASE_URL: postgres://namib:namib@postgres/namib_mud_controller
  script:
    - rustup target add $RUST_TRIPLE
    - cargo sqlx prepare -- --no-default-features --features postgres --lib
    - mv sqlx-data.json debian/sqlx-data.postgres.json
    - export DATABASE_URL=sqlite:db.sqlite
    - export MIGRATION_DIRECTORY=migrations/sqlite
    - ./scripts/recreate_db.sh
    - cargo sqlx prepare -- --lib
    - mv sqlx-data.json debian/sqlx-data.sqlite.json
    - dpkg --add-architecture $DEBIAN_ARCH
    - apt-get update
    - apt-get install git-secret build-essential crossbuild-essential-$DEBIAN_ARCH -y
    - apt-get build-dep -a $DEBIAN_ARCH . -y
    # download namib frontend
    - ./scripts/download_namib_frontend.sh
    # decrypt ca secret
    - gpg --import $GPG_PRIVATE_KEY
    - cd ..
    - git init && git remote add origin https://gitlab.informatik.uni-bremen.de/namib/mud-controller-enforcer/controller-enforcer-metaproject.git
    - git fetch origin && git checkout origin/master -f
    - git secret reveal
    - cd certs
    - ./gen_server_cert.sh namib-ca
    - cd ..
    - git secret hide
    - mv Cargo.toml Cargo.toml.thisisnotaworkspace
    - cd namib_mud_controller
    - dpkg-buildpackage --no-pre-clean --no-post-clean --host-arch $DEBIAN_ARCH
    - mkdir output
    - mv ../namib-mud-controller*.deb output/
    - mv ../namib-mud-controller*.buildinfo output/ || true
    - mv ../namib-mud-controller*.changes output/ || true
    - mv ../namib-mud-controller*.tar.gz output/ || true
    - mv ../namib-mud-controller*.dsc output/ || true
  artifacts:
    paths:
      - output

build-release-debian-amd64:
  extends: .build-release-debian
  variables:
    DEBIAN_ARCH: amd64
    RUST_TRIPLE: x86_64-unknown-linux-gnu

build-release-debian-arm64:
  extends: .build-release-debian
  variables:
    DEBIAN_ARCH: arm64
    RUST_TRIPLE: aarch64-unknown-linux-gnu

build-release-debian-armhf:
  extends: .build-release-debian
  variables:
    DEBIAN_ARCH: armhf
    RUST_TRIPLE: armv7-unknown-linux-gnueabihf

publish-github:
  extends: .namib_controller_base
  image: alpine:3
  stage: gh-release
  needs:
    - build-release-debian-amd64
    - build-release-debian-arm64
    - build-release-debian-armhf
    - !reference [.test_stage]
  only:
    refs:
      - tags
  before_script:
    - apk add --no-cache wget tar
    - wget -qO- https://github.com/cli/cli/releases/download/v1.10.3/gh_1.10.3_linux_amd64.tar.gz | tar -xvz --transform 's|^gh_1.10.3_linux_amd64/bin/||' -C /usr/local/bin gh_1.10.3_linux_amd64/bin
    - gh auth login --with-token < $GITHUB_RELEASE_TOKEN
  script:
    - gh release create $CI_COMMIT_TAG output/namib-mud-controller*.deb -R namib-project/namib_mud_controller

create-docker:
  extends: .namib_controller_base
  stage: docker
  needs:
    - build-release
    - !reference [.test_stage]
  cache: {}
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  only:
    refs:
      - main
  before_script: []
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $CI_REGISTRY_IMAGE:latest

create-docker-postgres:
  extends: .namib_controller_base
  stage: docker
  needs:
    - build-release-postgres
    - !reference [.test_stage]
  cache: {}
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  only:
    refs:
      - main
  before_script: []
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $CI_REGISTRY_IMAGE:postgres

.namib_controller_base:
  only:
    changes:
      - "namib_controller/**/*"
