/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Fork {
    #[serde(rename = "mud_url")]
    pub mud_url: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl Fork {
    pub fn new(mud_url: String, name: String) -> Fork {
        Fork { mud_url, name }
    }
}
