/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MudJson {
    #[serde(rename = "json")]
    pub json: String,
}

impl MudJson {
    pub fn new(json: String) -> MudJson {
        MudJson { json }
    }
}
