/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedThing {
    #[serde(rename = "serial", skip_serializing_if = "Option::is_none")]
    pub serial: Option<String>,
    #[serde(rename = "mac_addr", skip_serializing_if = "Option::is_none")]
    pub mac_addr: Option<String>,
    #[serde(rename = "ipv4_addr", skip_serializing_if = "Option::is_none")]
    pub ipv4_addr: Option<String>,
    #[serde(rename = "ipv6_addr", skip_serializing_if = "Option::is_none")]
    pub ipv6_addr: Option<String>,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
}

impl PatchedThing {
    #[allow(clippy::new_without_default)]
    pub fn new() -> PatchedThing {
        PatchedThing {
            serial: None,
            mac_addr: None,
            ipv4_addr: None,
            ipv6_addr: None,
            hostname: None,
        }
    }
}
