#!/bin/sh

# Adapted from postgresql-common postinstall script
if [ "$1" = configure ]; then
    if ! getent passwd namib-controller > /dev/null; then
        adduser --system --home /var/lib/namib \
            --shell /bin/sh --group --gecos "NAMIB Controller" namib-controller
    fi
fi