# TODO lets get the basic builds running first
#include:
#  - local: namib_enforcer/openwrt/package/.gitlab-ci.yml
#  - local: namib_enforcer/openwrt/image/.gitlab-ci.yml
include:
  - local: ///.common.yml

# every job should (transitively) inherit from this job template
.enf:job_base:
  only:
    changes:
      - "namib_enforcer/**/*"
  cache:
    - !reference [.pkg_cache]
    - &enf_cache
      key: "enf-native-$CI_COMMIT_REF_SLUG"
      paths:
        - target/*/deps/
        - target/*/incremental/
        - target/*/build/
      policy: pull
  before_script:
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de" > ~/.git-credentials
    - export CARGO_HOME=${CI_PROJECT_DIR}/.cargo
    - rustc --version
    - cargo --version

enf:build:
  extends: .enf:job_base
  stage: build
  cache:
    - !reference [.pkg_cache]
    - <<: *enf_cache
      policy: pull-push
  script:
    - if [ -z "$CI_COMMIT_TAG" ]; then cargo build -p namib_enforcer --release --features dnsmasq_hook; else cargo build -p namib_enforcer --features dnsmasq_hook; fi
  artifacts:
    paths:
      - target/*/namib_enforcer
      - target/*/namib_dnsmasq_hook
    expire_in: 7 days

enf:test:
  extends: .enf:job_base
  stage: test
  script:
    - cargo test -p namib_enforcer --features dnsmasq_hook

enf:warnings:
  extends: .enf:job_base
  stage: test
  script:
    - cargo clippy -p namib_enforcer -- -D warnings
  allow_failure: true

enf:formatting:
  extends: .enf:job_base
  stage: test
  script:
    - cargo fmt -p namib_enforcer -- --check

enf:docs:
  extends: .enf:job_base
  stage: docs
  needs:
    - enf:build
  except:
    - main
  script:
    - cargo doc -p namib_enforcer --no-deps --target-dir target-doc-enf
  artifacts:
    paths:
      - target-doc-enf/doc
    expire_in: 7 days

enf:pages:
  extends: .enf:job_base
  stage: docs
  only:
    refs:
      - main
  script:
    - cargo doc -p namib_enforcer --no-deps --target-dir target-doc-enf
    - mv target-doc-enf/doc public
    - echo '<meta http-equiv="refresh" content="0; url=namib_enforcer/index.html">' > public/index.html
  artifacts:
    paths:
      - public
    expire_in: 7 days

# TODO migrate to new monorepo on GitHub
.enf:publish-github:
  extends: .enf:job_base
  image: alpine:3
  stage: gh-release
  needs:
    - enf:openwrt_package_x86_64_21.02
    - enf:openwrt_package_bcm2708_21.02
    - enf:openwrt_package_bcm2710_21.02
    - enf:openwrt_package_bcm2711_21.02
  only:
    refs:
      - tags
  before_script:
    - apk add --no-cache wget tar
    - wget -qO- https://github.com/cli/cli/releases/download/v1.10.3/gh_1.10.3_linux_amd64.tar.gz | tar -xvz --transform 's|^gh_1.10.3_linux_amd64/bin/||' -C /usr/local/bin gh_1.10.3_linux_amd64/bin
    - gh auth login --with-token < $GITHUB_RELEASE_TOKEN
  script:
    - gh release create $CI_COMMIT_TAG output/namib_*.ipk output/dnsmasq-full_*.ipk -R namib-project/namib_enforcer
