include:
  - local: namib_enforcer/openwrt/package/.gitlab-ci.yml
  - local: namib_enforcer/openwrt/image/.gitlab-ci.yml

# every job should (transitively) inherit from this job template
.enf:job_base:
  only:
    changes:
      - "namib_enforcer/**/*"  
  before_script:
    - apt-get update && apt-get install -y libavahi-compat-libdnssd-dev libnftnl-dev libmnl-dev cmake clang
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.uni-bremen.de" > ~/.git-credentials
    - export CARGO_HOME=${CI_PROJECT_DIR}/.cargo
    - rustc --version
    - cargo --version

enf:build:
  extends: .enf:job_base
  stage: build
  script:
    - cargo build

enf:test:
  extends: .enf:job_base
  stage: test
  script:
    - cargo test --features dnsmasq_hook

enf:warnings:
  extends: .enf:job_base
  stage: test
  script:
    - rustup toolchain install nightly --component clippy --no-self-update
    - cargo +nightly clippy -- -D warnings
  allow_failure: true

enf:formatting:
  extends: .enf:job_base
  stage: test
  script:
    - rustup toolchain install nightly --component rustfmt --no-self-update
    - cargo +nightly fmt -- --check

enf:docs:
  extends: .enf:job_base
  stage: docs
  except:
    - main
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc
    expire_in: 7 days

enf:pages:
  extends: .enf:job_base
  stage: docs
  only:
    refs:
      - main
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=namib_enforcer/index.html">' > public/index.html
  artifacts:
    paths:
      - public
    expire_in: 7 days

enf:binary:
  extends: .enf:job_base
  stage: binary
  only:
    refs:
      - main
  script:
    - cargo build --features="dnsmasq_hook" --release
  artifacts:
    paths:
      - target/release/namib_enforcer
      - target/release/namib_dnsmasq_hook
    expire_in: 7 days

enf:publish-github:
  extends: .enf:job_base
  image: alpine:3
  stage: gh-release
  needs:
    - enf:openwrt_package_x86_64_21.02
    - enf:openwrt_package_bcm2708_21.02
    - enf:openwrt_package_bcm2710_21.02
    - enf:openwrt_package_bcm2711_21.02
  only:
    refs:
      - tags
  before_script:
    - apk add --no-cache wget tar
    - wget -qO- https://github.com/cli/cli/releases/download/v1.10.3/gh_1.10.3_linux_amd64.tar.gz | tar -xvz --transform 's|^gh_1.10.3_linux_amd64/bin/||' -C /usr/local/bin gh_1.10.3_linux_amd64/bin
    - gh auth login --with-token < $GITHUB_RELEASE_TOKEN
  script:
    - gh release create $CI_COMMIT_TAG output/namib_*.ipk output/dnsmasq-full_*.ipk -R namib-project/namib_enforcer
