#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=95

USE_PROCD=1
PROG=/usr/sbin/namib_enforcer

start_service() {
        procd_open_instance
        procd_set_param command "$PROG"
        procd_set_param env CA_CERT=/etc/namib/ca.pem
        procd_set_param env IDENTITY=/etc/namib/identity.pfx
        procd_set_param env RUST_LOG=info
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}
